### ISSUE TITLE
Error: 'peymanmo/eks-helm-deploy' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.

### ISSUE THREAD

**Issue by OliverRC** [peymanmortazavi/eks-helm-deploy#12]
> Error: 'peymanmo/eks-helm-deploy' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.

```
    - name: Deploy to EKS using Helm
      uses: peymanmortazavi/eks-helm-deploy@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1
        cluster-name: test-cluster
        namespace: test-development
        values: key1=value1,key2=value2
        name: test-1
        dry-run: true
```
