### ISSUE TITLE
failed to download repo

### ISSUE THREAD

**Issue by AwateAkshay** [peymanmortazavi/eks-helm-deploy#2]
@peymanmortazavi  I have added eks-helm-deploy job to my git workflow as shown below

```
- name: Deploy on EKS
  uses: peymanmortazavi/eks-helm-deploy@v1
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: us-west-1
    cluster-name: unitek-dev
    config-files: helm/unitek-open-banking-service/values.yaml
    namespace: monitoring
    name: unitek-open-banking-service
```
But unfortunately I'm facing this issue

```Download action repository 'peymanmortazavi/eks-helm-deploy@v1' (SHA:6740a4677efe6d80bd90945bf8eb1ef430fc3f4e)
Error: 'peymanmo/eks-helm-deploy' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
```
